#!/usr/bin/env bash
#
# For this script to work as intended, working directory should
# should be the directory the script is in.

WORKING_DIR=${PWD##*/}
SCRIPT_DIR=$(basename "$(cd "$(dirname "$0")" && pwd)")
SERVER_ONLY=false
START_SERVERS=false

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

show-help() {
	cat <<-EOF
	
	 This is a script to build the yatzy web app
	 and the server

	 Available commands:
	   -s | Start the servers after rebuilding
	   -b | Only build the server
	   -h | Show help
	
	EOF
}

build-server() {
	local output
	printf "\e[31mCompiling server...\e[0m"

	cd ./server/
	output=$(CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server 2>&1)
	if [[ $? = 0 ]]; then
		printf "\r\e[0K"
		printf "[\e[32m OK \e[0m] Compiling server done\n"
	else
		printf "\r\e[0K"
		printf "[\e[31m ERROR \e[0m] Compiling server failed!\n"
		sleep .2
		echo "$output"
		exit 1
	fi
	cd ..
}

build-web() {
	local output
	printf "\e[31mCompiling website...\e[0m"

	cd ./web/
	output=$(npm run build 2>&1)
	if [[ $? = 0 ]]; then
		printf "\r\e[0K"
		printf "[\e[32m OK \e[0m] Compiling website done\n"
	else
		printf "\r\e[0K"
		printf "[\e[31m ERROR \e[0m] Compiling website failed!\n"
		sleep .2
		echo "$output"
		exit 1
	fi
	cd ..
}

main() {
	if [[ $WORKING_DIR != $SCRIPT_DIR ]]; then
		fatal 'wrong directory'
	fi
	local OPTARG OPTIND opt
	while getopts 'hsb' opt; do
		case "$opt" in
			s) START_SERVERS=true;;
			b) SERVER_ONLY=true;;
			h)
				show-help
				exit 0
				;;
			*) fatal 'Bad option, use -h for help';;
		esac
	done

	build-server
	if [[ $SERVER_ONLY = false ]]; then
		build-web
	fi

	sleep .5
	if [[ $START_SERVERS = true ]]; then
		printf "\e[31mStopping existing server...\e[0m\n"
		docker compose down

		sleep .2
		printf "\e[32mStarting server...\e[0m\n"
		sleep .5
		docker compose up --build
	fi
}

main "$@"
