#!/usr/bin/env bash
#
# For this script to work, you have to be in the same
# directory the script is in.
# The script also partly enforces that by checking
# that the directory the script is run in has the
# correct name, but that obviously doesn't make it
# impossible to run the script at locations where it
# wasnt designed to be run

DIR=${PWD##*/}
RUN=false

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

show-help() {
	cat <<-EOF
	
	 Backend server build script for this yatzy project.

	 This script builds the server in backend/ and if
	 given the 'r' option runs the server
	 The script clears the screen, but it keeps scrollback,
	 so you can still see what was previously on the screen
	

	 Available commands:
	   -h | Show help
	   -r | [OPTIONAL] automatically runs the servers
	
	EOF
}

main() {
	if [[ $DIR != "yatzy" ]]; then
		fatal 'wrong directory'
	fi
	local OPTARG OPTIND opt
	while getopts 'hr' opt; do
		case "$opt" in
			r) RUN=true ;;
			h)
				show-help
				exit 0
				;;
			*) fatal 'Bad option, use -h for help';;
		esac
	done

	printf "\e[31mBuilding...\e[0m"
	cd ./backend/
	go build
	cd ..
	printf "\r\e[0K" # clear the line
	printf "\e[32mBuilding done\e[0m\n"
	sleep .2

	printf '\e[H\e[2J'


	if [[ "$RUN" = true ]]; then
		./start-servers
	fi
}

main "$@"
