#!/usr/bin/env bash
#
# For this script to work, you have to be in the same
# directory the script is in.
# The script also partly enforces that by checking
# that the directory the script is run in has the
# correct name, but that obviously doesn't make it
# impossible to run the script at locations where it
# wasnt designed to be run

DIR=${PWD##*/}
SERVER_ONLY=false

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

show-help() {
	cat <<-EOF
	
	 This is a script to rebuild the yatzy web app
	 and the server to serve the app

	 Available commands:
	   -s | Only rebuild the server
	   -h | Show help
	
	EOF
}

main() {
	if [[ $DIR != "yatzy" ]]; then
		fatal 'wrong directory'
	fi
	local OPTARG OPTIND opt
	while getopts 'hs' opt; do
		case "$opt" in
			s) SERVER_ONLY=true;;
			h)
				show-help
				exit 0
				;;
			*) fatal 'Bad option, use -h for help';;
		esac
	done

	printf "\e[31mBuilding server...\e[0m"
	cd ./server/
	go build
	cd ..
	printf "\r\e[0K" # clear the line
	printf "\e[32mBuilding server done\e[0m\n"

	if [[ $SERVER_ONLY = false ]]; then
		printf "\e[31mCompiling website...\e[0m"
		cd ./web/
		npm run build >/dev/null
		cd ..
		printf "\r\e[0K" # clear the line
		printf "\e[32mCompiling website done\e[0m\n"
	fi
}

main "$@"
