#!/usr/bin/env bash
#
# For this script to work, you have to be in the same
# directory the script is in.
# The script also partly enforces that by checking
# that the directory the script is run in has the
# correct name, but that obviously doesn't make it
# impossible to run the script at locations where it
# wasnt designed to be run

DIR=${PWD##*/}

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

show-help() {
	cat <<-EOF
	
	 Backend server build script for this yatzy project.

	 This script builds the server in backend/

	 The script clears the screen, but it keeps scrollback,
	 so you can still see what was previously on the screen
	

	 Available commands:
	   -h | Show help
	
	EOF
}

main() {
	if [[ $DIR != "yatzy" ]]; then
		fatal 'wrong directory'
	fi
	local OPTARG OPTIND opt
	while getopts 'hr' opt; do
		case "$opt" in
			h)
				show-help
				exit 0
				;;
			*) fatal 'Bad option, use -h for help';;
		esac
	done

	printf "\e[31mBuilding...\e[0m"
	cd ./db-api/
	go build
	cd ..
	printf "\r\e[0K" # clear the line
	printf "\e[32mBuilding done\e[0m\n"
}

main "$@"
