#!/usr/bin/env bash
#
# A script to start the frontend and 
# backend into a tmux session so that
# they are easy to manage and kill

SESSION="yatzy-servers"

tmux new-session -d -s "$SESSION" -n "frontend" "npm run dev"

tmux new-window -t "$SESSION" -n "backend" "./backend/backend"

