#!/usr/bin/env bash
#
# A script to start the frontend and 
# backend into a tmux session so that
# they are easy to manage and kill

ATTACH=false

fatal() {
	echo '[FATAL]' "$@" >&2
	exit 1
}

main() {
	local OPTARG OPTIND opt
	while getopts 'a' opt; do
		case "$opt" in
			a) ATTACH=true;;
			*) fatal 'Bad option, use -h for help';;
		esac
	done

	printf "\e[31mStarting servers...\e[0m"
	SESSION="yatzy-servers"

	tmux new-session -d -s "$SESSION" -n "server" "./server/server"

	printf "\r\e[0K" # clear the line
	printf "\e[32mServers started\e[0m\n"

	echo To close the servers:
	echo '    tmux kill-session'
	echo or if there is multiple tmux sessions:
	echo '    tmux kill-session -t yatzy-servers'

	if [[ $ATTACH = true ]]; then
		tmux a
	fi

}

main "$@"
